/**
 * Static QR code linking to the shared photo album. The SVG itself is
 * pre-generated by scripts/gen-qr.mjs from links.memoriesDrive — this
 * component just renders it, no runtime QR generation.
 */
export default function QrCode() {
  return (
    <img
      src={`${import.meta.env.BASE_URL}img/qr-drive.svg`}
      width={160}
      height={160}
      alt="QR code linking to the shared photo album"
      className="rounded-xl border border-paper-deep bg-paper-card p-3 shadow-card"
    />
  )
}
